# Master key: 9e1678c03006782a94911992f91d63ea

twitter:
  client_id: cHBHRUx1YllKbVZMRUh5Z2pyd0g6MTpjaQ
  client_secret: hEGV72WwhYPfoiO4d1KYaZfyLLO_AfxBsH43Dq8rIM0TeDYGTu
  auth_token: " AAAAAAAAAAAAAAAAAAAAANpIxwEAAAAAvzPuitW%2BsynsYxKWi3wAY3q2nRk%3DUi3sTAnEThLwodtPzXfLr33lWow8zrIFxvEUYXAfzzzmX7zSO8"
  api_key: nge2mXS56XtxSjqboiZKSifdI
  api_secret: DKkS35yvB4vxrKQOKPgq4J5Npid4Sp3sSyQn8dacJ2qLBHrToa

database:
  host: localhost
  post: 5432
  name: social_engagement_development
  username: postgres
  password: postgres

cache_time: 0 # hours
batch_size: 10
schedule_interval: 5 seconds
ui_host: http://localhost:5173
twitter_tags: "#TKNTEST,@JMPTEST"

jwt_secret_key: '5DyZq60XG9gJHqjk83Ryi4gFfrI5KHlSVkE4'
enable_sync: true
login_expiry_time: 1

# SKALE
network:
  skale:
    private_key: 0x391a84b0464e0f134d7121c60b95ac058f2c5b7a8ab9d8daa65a3eba45ff2a6a
    public_address: 0x558C447ead86B5Dcc3F7434c0b5206f724A86AE0
    rpc: https://staging-v3.skalenodes.com/v1/staging-faint-slimy-achird
    explorer: https://staging-faint-slimy-achird.explorer.staging-v3.skalenodes.com
    decimals: 18
    credits_ratio: 0.000001
    token:
      contract: '0xd8220e4525A8a433586BE429742dDe60fa57259a'
      abi: 'lib/network/abi/skl.json'
# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: 47f2a010d581a596d674c7cd8d76d86e9a69b35645850449b2abfa54ccee9c6c860c66bc4b0fb83720bb8c7dd99a40a9f7c5ec9c5646545af038b63cdc9c840a
